// src/config/env.js
const { ADMIN_IDS, CHANNELS, ROLES, EMOJIS } = require("./ids");

const DISCORD_TOKEN = process.env.DISCORD_TOKEN;
const APPLICATION_ID = process.env.APPLICATION_ID;

module.exports = {
  DISCORD_TOKEN,
  APPLICATION_ID,

  // Admin & IDs from ids.js
  ADMIN_IDS,
  ADMIN_ID: ADMIN_IDS[0], // Main admin ID

  // Role IDs
  TEMP_ROLE_ID: ROLES.TEMP_ROLE,
  PERMANENT_ROLE_ID: ROLES.PERMANENT_ROLE,

  // Channel IDs
  GENERAL_CHAT_CHANNEL_ID: CHANNELS.GENERAL_CHAT,
  IMAGE_UPLOAD_CHANNEL_ID: CHANNELS.IMAGE_UPLOAD,
  AI_CHANNELS: CHANNELS.AI_CHAT,
  WORDCHAIN_CHANNEL_ID: CHANNELS.WORDCHAIN,
  WORDSCRAMBLE_CHANNEL_ID: CHANNELS.WORDSCRAMBLE,
  RULES_CHANNEL_ID: CHANNELS.RULES,
  WUWA_CODES_CHANNEL_ID: CHANNELS.WUWA_CODES,
  WUWA_ROLE_ID: ROLES.WUWA_ROLE || "1528768731873017896",
  WUWA_EMOJI_ID: (EMOJIS && EMOJIS.WUWA_ICON) || "1536322393411424286",

  // Gemini config (Model: gemini-3.1-flash-lite)
  GEMINI_API_KEYS: (process.env.GEMINI_API_KEYS || "").split(","),
  GEMINI_MODEL_URL: "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key=",

  // Webhooks
  WEBHOOK_WORDCHAIN: process.env.WEBHOOK_WORDCHAIN,
  WEBHOOK_WORDSCRAMBLE: process.env.WEBHOOK_WORDSCRAMBLE,
  WEBHOOK_WUWA_CODES: process.env.WEBHOOK_WUWA_CODES,
  WEBHOOKS: {
    HAPPY: process.env.WEBHOOK_HAPPY,
    PLAYFUL: process.env.WEBHOOK_PLAYFUL,
    THINKING: process.env.WEBHOOK_THINKING,
    ANGRY: process.env.WEBHOOK_ANGRY,
    WORDCHAIN: process.env.WEBHOOK_WORDCHAIN,
    WORDSCRAMBLE: process.env.WEBHOOK_WORDSCRAMBLE,
    WUWA_CODES: process.env.WEBHOOK_WUWA_CODES,
  },
};
